"""
Request correlation middleware tests.

Every HTTP response must carry X-Request-ID. If the client sends one, echo it.
Otherwise generate a UUID4. The ID must appear in log records emitted during
request processing. Error responses must also carry the header.
"""
import logging
import uuid

import pytest
from fastapi.testclient import TestClient
from unittest.mock import AsyncMock, MagicMock

from src.api.app import create_app
from src.api.auth import create_token
from src.api.ea_registry import EARegistry


def _test_app(**overrides):
    ea = AsyncMock()
    ea.handle_customer_interaction = AsyncMock(return_value="ok")
    defaults = dict(
        ea_registry=EARegistry(factory=lambda cid: ea),
        orchestrator=AsyncMock(),
        whatsapp_manager=MagicMock(),
        redis_client=AsyncMock(),
    )
    defaults.update(overrides)
    return create_app(**defaults)


@pytest.fixture
def client():
    return TestClient(_test_app())


@pytest.fixture
def auth_headers():
    tok = create_token("cust_corr")
    return {"Authorization": f"Bearer {tok}"}


class TestClientProvidedId:
    def test_echoes_client_request_id(self, client):
        resp = client.get(
            "/healthz", headers={"X-Request-ID": "my-custom-id-123"}
        )
        assert resp.headers["X-Request-ID"] == "my-custom-id-123"

    def test_preserves_exact_value(self, client):
        weird_id = "FOO-bar_baz.123"
        resp = client.get(
            "/healthz", headers={"X-Request-ID": weird_id}
        )
        assert resp.headers["X-Request-ID"] == weird_id


class TestAutoGeneratedId:
    def test_generates_valid_uuid4(self, client):
        resp = client.get("/healthz")
        rid = resp.headers["X-Request-ID"]
        parsed = uuid.UUID(rid, version=4)
        assert str(parsed) == rid

    def test_distinct_ids_per_request(self, client):
        ids = {client.get("/healthz").headers["X-Request-ID"] for _ in range(5)}
        assert len(ids) == 5


class TestHeaderOnAllRoutes:
    def test_health(self, client):
        assert "X-Request-ID" in client.get("/healthz").headers

    def test_readiness(self, client):
        # Redis mock may fail — that's fine, we just need the header
        resp = client.get("/readyz")
        assert "X-Request-ID" in resp.headers

    def test_conversations(self, client, auth_headers):
        resp = client.post(
            "/v1/conversations/message",
            json={"message": "hi", "channel": "chat"},
            headers=auth_headers,
        )
        assert "X-Request-ID" in resp.headers

    def test_provisioning(self, client):
        resp = client.post(
            "/v1/customers/provision",
            json={"customer_id": "cust_corr_prov", "tier": "basic"},
        )
        assert "X-Request-ID" in resp.headers


class TestHeaderOnErrors:
    def test_401_unauthorized(self, client):
        resp = client.post(
            "/v1/conversations/message",
            json={"message": "hi", "channel": "chat"},
        )
        assert resp.status_code == 401
        assert "X-Request-ID" in resp.headers

    def test_422_validation(self, client, auth_headers):
        resp = client.post(
            "/v1/conversations/message",
            json={"channel": "chat"},  # missing message
            headers=auth_headers,
        )
        assert resp.status_code == 422
        assert "X-Request-ID" in resp.headers

    def test_503_service_unavailable(self):
        broken_ea = AsyncMock()
        broken_ea.handle_customer_interaction = AsyncMock(
            side_effect=ConnectionError("boom")
        )
        app = create_app(
            ea_registry=EARegistry(factory=lambda cid: broken_ea),
            orchestrator=AsyncMock(),
            whatsapp_manager=MagicMock(),
            redis_client=AsyncMock(),
        )
        client = TestClient(app)
        tok = create_token("cust_err")
        resp = client.post(
            "/v1/conversations/message",
            json={"message": "hi", "channel": "chat"},
            headers={"Authorization": f"Bearer {tok}"},
        )
        assert resp.status_code == 503
        assert "X-Request-ID" in resp.headers


class TestCorrelationInLogs:
    def test_log_records_contain_correlation_id(self, auth_headers):
        app = _test_app()
        client = TestClient(app)

        handler = logging.Handler()
        handler.setLevel(logging.DEBUG)
        records: list[logging.LogRecord] = []
        handler.emit = lambda record: records.append(record)
        logging.getLogger().addHandler(handler)

        try:
            client.post(
                "/v1/conversations/message",
                json={"message": "hi", "channel": "chat"},
                headers=auth_headers,
            )
        finally:
            logging.getLogger().removeHandler(handler)

        # At least one log record should have the correlation_id attribute
        corr_records = [r for r in records if hasattr(r, "correlation_id")]
        assert len(corr_records) > 0
        # And they should all have the same ID for this request
        ids = {r.correlation_id for r in corr_records}
        assert len(ids) == 1
