"""
Request correlation ID middleware.

Every HTTP response — success or error — must carry X-Request-ID.
Client-provided IDs are echoed unchanged; auto-generated IDs are
UUID4. The ID propagates to log records via contextvar + filter.
"""
import logging
import uuid

import pytest
from fastapi.testclient import TestClient
from unittest.mock import AsyncMock, MagicMock

from src.api.app import create_app
from src.api.auth import create_token
from src.api.ea_registry import EARegistry


def _app(**overrides):
    ea = overrides.pop("ea", None) or AsyncMock()
    if not hasattr(ea, "handle_customer_interaction") or \
       not callable(getattr(ea.handle_customer_interaction, "__call__", None)):
        ea.handle_customer_interaction = AsyncMock(return_value="reply")
    registry = overrides.pop("ea_registry", None) or EARegistry(factory=lambda cid: ea)
    return create_app(
        ea_registry=registry,
        orchestrator=overrides.get("orchestrator") or AsyncMock(),
        whatsapp_manager=overrides.get("whatsapp_manager") or MagicMock(),
        redis_client=overrides.get("redis_client") or AsyncMock(),
    )


@pytest.fixture
def client():
    return TestClient(_app(), raise_server_exceptions=False)


@pytest.fixture
def auth_headers():
    tok = create_token("cust_corr")
    return {"Authorization": f"Bearer {tok}"}


class TestClientProvidedId:
    def test_echoed_unchanged_on_healthz(self, client):
        resp = client.get("/healthz", headers={"X-Request-ID": "fixed-id-123"})
        assert resp.status_code == 200
        assert resp.headers["X-Request-ID"] == "fixed-id-123"

    def test_echoed_on_conversation_post(self, auth_headers):
        ea = AsyncMock()
        ea.handle_customer_interaction = AsyncMock(return_value="hi")
        app = _app(ea=ea)
        client = TestClient(app)
        resp = client.post(
            "/v1/conversations/message",
            json={"message": "hello", "channel": "chat"},
            headers={**auth_headers, "X-Request-ID": "conv-trace-7"},
        )
        assert resp.status_code == 200
        assert resp.headers["X-Request-ID"] == "conv-trace-7"


class TestAutoGeneratedId:
    def test_generated_is_uuid4(self, client):
        resp = client.get("/healthz")
        cid = resp.headers["X-Request-ID"]
        parsed = uuid.UUID(cid)
        assert parsed.version == 4

    def test_two_requests_get_distinct_ids(self, client):
        a = client.get("/healthz").headers["X-Request-ID"]
        b = client.get("/healthz").headers["X-Request-ID"]
        assert a != b


class TestHeaderOnAllResponses:
    @pytest.mark.parametrize("path", ["/healthz", "/readyz"])
    def test_health_endpoints(self, client, path):
        resp = client.get(path)
        assert "X-Request-ID" in resp.headers

    def test_on_401_unauthorized(self, client):
        resp = client.post(
            "/v1/conversations/message",
            json={"message": "hi", "channel": "chat"},
        )
        assert resp.status_code == 401
        assert "X-Request-ID" in resp.headers

    def test_on_422_validation_error(self, client, auth_headers):
        resp = client.post(
            "/v1/conversations/message",
            json={"message": "", "channel": "chat"},
            headers=auth_headers,
        )
        assert resp.status_code == 422
        assert "X-Request-ID" in resp.headers

    def test_on_404_not_found(self, client):
        resp = client.get("/no-such-route")
        assert resp.status_code == 404
        assert "X-Request-ID" in resp.headers

    def test_on_503_ea_raises(self):
        """
        EA handle_customer_interaction raises → route's broad except
        converts to ServiceUnavailableError → 503. Middleware still
        stamps the header on the error response.
        """
        ea = AsyncMock()
        ea.handle_customer_interaction = AsyncMock(
            side_effect=RuntimeError("boom"))
        app = _app(ea=ea)
        client = TestClient(app, raise_server_exceptions=False)
        tok = create_token("cust_503")
        resp = client.post(
            "/v1/conversations/message",
            json={"message": "hi", "channel": "chat"},
            headers={"Authorization": f"Bearer {tok}"},
        )
        assert resp.status_code == 503, resp.text
        assert resp.json()["type"] == "service_unavailable"
        assert "X-Request-ID" in resp.headers

    def test_on_503_registry_raises(self, auth_headers):
        """
        EARegistry.get() raises → route catches → 503. Same header
        guarantee.
        """
        broken_registry = MagicMock()
        broken_registry.get = AsyncMock(
            side_effect=ConnectionError("redis down"))
        app = _app(ea_registry=broken_registry)
        client = TestClient(app, raise_server_exceptions=False)
        resp = client.post(
            "/v1/conversations/message",
            json={"message": "hi", "channel": "chat"},
            headers=auth_headers,
        )
        assert resp.status_code == 503, resp.text
        assert resp.json()["type"] == "service_unavailable"
        assert "X-Request-ID" in resp.headers


class TestLogPropagation:
    def test_log_record_carries_correlation_id(self, caplog):
        """
        Log lines emitted during request processing must have a
        correlation_id attribute. The LogRecord factory (installed by
        create_app) injects it from the contextvar at record creation.
        """
        app = _app()
        client = TestClient(app)
        with caplog.at_level(logging.DEBUG, logger="src.api.routes.health"):
            client.get("/readyz", headers={"X-Request-ID": "log-trace-9"})
        # /readyz emits a debug log; find it.
        cids = [
            getattr(r, "correlation_id", None)
            for r in caplog.records
            if r.name == "src.api.routes.health"
        ]
        assert "log-trace-9" in cids, \
            f"No readyz record carried correlation_id=log-trace-9. Got: {cids}"

    def test_get_correlation_id_default_outside_request(self):
        """Outside a request, the contextvar holds the default '-'."""
        from src.api.correlation import get_correlation_id
        assert get_correlation_id() == "-"


class TestJSONFormatterCorrelationId:
    def test_formatter_picks_up_correlation_id_attribute(self):
        """JSONFormatter must serialize correlation_id when present."""
        import json
        from src.utils.logging import JSONFormatter
        record = logging.LogRecord(
            name="test", level=logging.INFO, pathname="x", lineno=1,
            msg="hello", args=(), exc_info=None,
        )
        record.correlation_id = "abc-123"
        out = json.loads(JSONFormatter().format(record))
        assert out["correlation_id"] == "abc-123"

    def test_formatter_default_when_no_attribute(self):
        """No correlation_id on the record → '-' in output (or absent).
        Spec says getattr(record, 'correlation_id', '-')."""
        import json
        from src.utils.logging import JSONFormatter
        record = logging.LogRecord(
            name="test", level=logging.INFO, pathname="x", lineno=1,
            msg="hello", args=(), exc_info=None,
        )
        out = json.loads(JSONFormatter().format(record))
        assert out.get("correlation_id") == "-"
