"""
Request correlation middleware tests.

Every HTTP response must carry X-Request-ID. If the client sends one, echo it.
Otherwise generate a UUID4. The ID must appear in log records emitted during
request processing. Error responses must also carry the header.
"""
import logging
import uuid

import pytest
from fastapi.testclient import TestClient
from unittest.mock import AsyncMock, MagicMock

from src.api.app import create_app
from src.api.auth import create_token
from src.api.ea_registry import EARegistry


def _mock_orchestrator():
    """Orchestrator that returns properly typed env objects."""
    orch = AsyncMock()

    async def _provision(customer_id, tier="professional", **_):
        env = MagicMock()
        env.customer_id = customer_id
        env.tier = tier
        return env

    orch.provision_customer_environment = AsyncMock(side_effect=_provision)
    return orch


def _test_app(**overrides):
    ea = AsyncMock()
    ea.handle_customer_interaction = AsyncMock(return_value="ok")
    defaults = dict(
        ea_registry=EARegistry(factory=lambda cid: ea),
        orchestrator=_mock_orchestrator(),
        whatsapp_manager=MagicMock(),
        redis_client=AsyncMock(),
    )
    defaults.update(overrides)
    return create_app(**defaults)


@pytest.fixture
def client():
    return TestClient(_test_app())


@pytest.fixture
def auth_headers():
    tok = create_token("cust_corr")
    return {"Authorization": f"Bearer {tok}"}


class TestClientProvidedId:
    def test_echoes_client_request_id(self, client):
        resp = client.get(
            "/healthz", headers={"X-Request-ID": "my-custom-id-123"}
        )
        assert resp.headers["X-Request-ID"] == "my-custom-id-123"

    def test_preserves_exact_value(self, client):
        weird_id = "FOO-bar_baz.123"
        resp = client.get(
            "/healthz", headers={"X-Request-ID": weird_id}
        )
        assert resp.headers["X-Request-ID"] == weird_id


class TestAutoGeneratedId:
    def test_generates_valid_uuid4(self, client):
        resp = client.get("/healthz")
        rid = resp.headers["X-Request-ID"]
        parsed = uuid.UUID(rid, version=4)
        assert str(parsed) == rid

    def test_distinct_ids_per_request(self, client):
        ids = {client.get("/healthz").headers["X-Request-ID"] for _ in range(5)}
        assert len(ids) == 5


class TestHeaderOnAllRoutes:
    def test_health(self, client):
        assert "X-Request-ID" in client.get("/healthz").headers

    def test_readiness(self, client):
        # Redis mock may fail — that's fine, we just need the header
        resp = client.get("/readyz")
        assert "X-Request-ID" in resp.headers

    def test_conversations(self, client, auth_headers):
        resp = client.post(
            "/v1/conversations/message",
            json={"message": "hi", "channel": "chat"},
            headers=auth_headers,
        )
        assert "X-Request-ID" in resp.headers

    def test_provisioning(self, client):
        resp = client.post(
            "/v1/customers/provision",
            json={"customer_id": "cust_corr_prov", "tier": "basic"},
        )
        assert "X-Request-ID" in resp.headers


class TestHeaderOnErrors:
    def test_401_unauthorized(self, client):
        resp = client.post(
            "/v1/conversations/message",
            json={"message": "hi", "channel": "chat"},
        )
        assert resp.status_code == 401
        assert "X-Request-ID" in resp.headers

    def test_422_validation(self, client, auth_headers):
        resp = client.post(
            "/v1/conversations/message",
            json={"channel": "chat"},  # missing message
            headers=auth_headers,
        )
        assert resp.status_code == 422
        assert "X-Request-ID" in resp.headers

    def test_503_service_unavailable(self):
        broken_ea = AsyncMock()
        broken_ea.handle_customer_interaction = AsyncMock(
            side_effect=ConnectionError("boom")
        )
        app = create_app(
            ea_registry=EARegistry(factory=lambda cid: broken_ea),
            orchestrator=AsyncMock(),
            whatsapp_manager=MagicMock(),
            redis_client=AsyncMock(),
        )
        client = TestClient(app)
        tok = create_token("cust_err")
        resp = client.post(
            "/v1/conversations/message",
            json={"message": "hi", "channel": "chat"},
            headers={"Authorization": f"Bearer {tok}"},
        )
        assert resp.status_code == 503
        assert "X-Request-ID" in resp.headers


class TestCorrelationInLogs:
    def test_log_records_contain_correlation_id(self, caplog):
        """
        Trigger a 503 (EA exception) so the error handler emits a log
        line. The correlation filter should inject the ID into it.
        """
        broken_ea = AsyncMock()
        broken_ea.handle_customer_interaction = AsyncMock(
            side_effect=ConnectionError("boom")
        )
        app = create_app(
            ea_registry=EARegistry(factory=lambda cid: broken_ea),
            orchestrator=_mock_orchestrator(),
            whatsapp_manager=MagicMock(),
            redis_client=AsyncMock(),
        )
        client = TestClient(app)
        tok = create_token("cust_log")

        with caplog.at_level(logging.DEBUG):
            client.post(
                "/v1/conversations/message",
                json={"message": "hi", "channel": "chat"},
                headers={"Authorization": f"Bearer {tok}"},
            )

        # The log-record factory injects correlation_id into every
        # LogRecord at creation time. caplog captures these.
        app_records = [
            r for r in caplog.records
            if hasattr(r, "correlation_id") and r.name != "httpx"
        ]
        assert len(app_records) > 0, (
            f"No records with correlation_id; captured {len(caplog.records)} total: "
            f"{[(r.name, hasattr(r, 'correlation_id')) for r in caplog.records]}"
        )
        ids = {r.correlation_id for r in app_records if r.correlation_id != "-"}
        assert len(ids) == 1
